// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoEizZOOmx1i3FSxKs42kAKKnCKrlhq-0',
    appId: '1:681309908823:web:7ba6d2fe8690c0b0221812',
    messagingSenderId: '681309908823',
    projectId: 'campusconncet2',
    authDomain: 'campusconncet2.firebaseapp.com',
    storageBucket: 'campusconncet2.appspot.com',
    measurementId: 'G-ZRVFC34M8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_-HbR3xlsO0PrPyK355ZsoqOPGbInn7s',
    appId: '1:681309908823:android:0d12979ff0865e3c221812',
    messagingSenderId: '681309908823',
    projectId: 'campusconncet2',
    storageBucket: 'campusconncet2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0rKAa_515fTT1ktOhOEort8432QwcL7I',
    appId: '1:681309908823:ios:e153827850eeef12221812',
    messagingSenderId: '681309908823',
    projectId: 'campusconncet2',
    storageBucket: 'campusconncet2.appspot.com',
    iosBundleId: 'com.example.campusconnect2',
  );
}
